Fix typo in field access, purchaseable->purchasable
Fixes `AttributeError: 'GoldData' object has no attribute 'purchaseable'`

I don't think this is a breaking change because anything using this would throw an exception.