Fix crash when loading accounts (#467)
This would previously fail with the following error:

      File ".../cassiopeia/datastores/riotapi/account.py", line 89, in get_account
        data["region"] = query["platform"].region.value
        ~~~~^^^^^^^^^^
    TypeError: 'str' object does not support item assignment